from __future__ import annotations

import json
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ._skill_paths import firm_dir, firm_meta_path


def _escape(s: str) -> str:
    """Escape characters that would break a markdown table cell."""
    return s.replace("|", "\\|").replace("\n", " ")


def _md_table(headers: list[str], rows: list[list[str]]) -> str:
    if not rows:
        return "(no values)\n"
    out = ["| " + " | ".join(headers) + " |"]
    out.append("| " + " | ".join("---" for _ in headers) + " |")
    for row in rows:
        out.append("| " + " | ".join(_escape(str(c)) for c in row) + " |")
    return "\n".join(out) + "\n"


def render_categories_md(fetched: dict[str, list[dict[str, Any]]]) -> str:
    """Render every category type + its values as one markdown doc."""
    sections = [
        "# Firm Categories\n",
        "_Generated by `wbox skills bootstrap`. Refresh with `wbox skills refresh`._\n",
    ]
    for type_name in sorted(fetched):
        sections.append(f"## {type_name}\n")
        values = fetched[type_name]
        rows = [[str(v.get("id", "")), str(v.get("name", ""))] for v in values]
        sections.append(_md_table(["id", "name"], rows))
    return "\n".join(sections)


def render_custom_fields_md(fetched: dict[str, list[dict[str, Any]]]) -> str:
    """Render custom fields grouped by document type with valid options inline."""
    sections = [
        "# Firm Custom Fields\n",
        "_Generated by `wbox skills bootstrap`. Refresh with `wbox skills refresh`._\n",
    ]
    for doc_type in sorted(fetched):
        sections.append(f"## {doc_type}\n")
        fields = fetched[doc_type]
        rows: list[list[str]] = []
        for f in fields:
            options = f.get("options") or []
            option_names = (
                ", ".join(o.get("label") or o.get("name", "") for o in options)
                if options else "-"
            )
            rows.append(
                [
                    str(f.get("id", "")),
                    str(f.get("name", "")),
                    str(f.get("field_type", "")),
                    option_names,
                ]
            )
        sections.append(_md_table(["id", "name", "type", "options"], rows))
    return "\n".join(sections)


def render_users_md(users: list[dict[str, Any]]) -> str:
    sections = [
        "# Firm Users\n",
        "_Generated by `wbox skills bootstrap`. Refresh with `wbox skills refresh`._\n",
    ]
    rows = [
        [str(u.get("id", "")), str(u.get("name", "")), str(u.get("email", ""))]
        for u in users
    ]
    if not rows:
        sections.append("(no users)\n")
    else:
        sections.append(_md_table(["id", "name", "email"], rows))
    return "\n".join(sections)


# --------------------------------------------------------------------------- #
# Stubs                                                                        #
# --------------------------------------------------------------------------- #

FIRM_README = """# firm/ — Firm Customizations

This folder holds everything the agent needs to know about your firm's
Wealthbox conventions. Firm metadata lives in `_meta.json` next to this
file (canonical, machine-level — survives plugin auto-updates).

Per-install template version lives in `<skill_dir>/_meta.json` (one per
installed platform).

## Generated files (overwritten by `wbox skills refresh`)

- `categories.md` — every category type + valid values
- `custom-fields.md` — custom fields per document type + valid values
- `users.md` — user id -> name -> email

## Hand-edited files (never overwritten)

- `contacts.md`, `tasks.md`, `notes.md`, `events.md`,
  `opportunities.md`, `projects.md`, `workflows.md`

Each hand-edited file has a matching example in any installed skill's
`firm-examples/` directory.
"""


def _stub(resource: str) -> str:
    return (
        f"# firm/{resource} — Firm Policy\n\n"
        f"_Stub — first-run bootstrap will populate this via the agent._\n\n"
        f"See `firm-examples/{resource}` for a filled-in reference.\n\n"
        f"TODO: capture firm policy for {resource[:-3]} here.\n"
    )


STUB_CONTENTS: dict[str, str] = {
    "contacts.md": _stub("contacts.md"),
    "tasks.md": _stub("tasks.md"),
    "notes.md": _stub("notes.md"),
    "events.md": _stub("events.md"),
    "opportunities.md": _stub("opportunities.md"),
    "projects.md": _stub("projects.md"),
    "workflows.md": _stub("workflows.md"),
}


def write_stubs(target_firm_dir: Path) -> list[str]:
    """Write stub files that don't already exist. Returns list of names written."""
    written: list[str] = []
    for name, body in STUB_CONTENTS.items():
        path = target_firm_dir / name
        if path.exists():
            continue
        path.write_text(body, encoding="utf-8")
        written.append(name)
    readme = target_firm_dir / "_README.md"
    if not readme.exists():
        readme.write_text(FIRM_README, encoding="utf-8")
    return written


# --------------------------------------------------------------------------- #
# Per-install template metadata (one _meta.json per skill dir)                 #
# --------------------------------------------------------------------------- #

def meta_path(skill_dir: Path) -> Path:
    """Location of _meta.json relative to a skill install root."""
    return skill_dir / "_meta.json"


def read_meta(skill_dir: Path) -> dict[str, Any]:
    """Read `<skill_dir>/_meta.json`. Returns {} if missing or unreadable.

    The per-install meta only carries the `template` section after the
    canonical-firm-path refactor; firm state lives in `firm_meta_path()`.
    """
    p = meta_path(skill_dir)
    if not p.exists():
        return {}
    try:
        loaded = json.loads(p.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}
    return loaded if isinstance(loaded, dict) else {}


def write_meta(skill_dir: Path, data: dict[str, Any]) -> None:
    meta_path(skill_dir).write_text(
        json.dumps(data, indent=2) + "\n", encoding="utf-8"
    )


def update_template_meta(skill_dir: Path, *, cli_version: str) -> None:
    """Set the template section of `<skill_dir>/_meta.json`."""
    meta = read_meta(skill_dir)
    meta["template"] = {"cli_version": cli_version}
    write_meta(skill_dir, meta)


# --------------------------------------------------------------------------- #
# Canonical firm metadata (one _meta.json per machine, at firm_meta_path())    #
# --------------------------------------------------------------------------- #

def read_firm_meta() -> dict[str, Any]:
    """Read the canonical firm meta JSON. Returns {} if missing or unreadable."""
    p = firm_meta_path()
    if not p.exists():
        return {}
    try:
        loaded = json.loads(p.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}
    return loaded if isinstance(loaded, dict) else {}


def write_firm_meta(data: dict[str, Any]) -> None:
    p = firm_meta_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def update_firm_meta(
    *,
    identity: dict[str, Any],
    cli_version: str,
    generated_files: list[str],
) -> None:
    """Write firm identity + generated-file timestamps to canonical firm meta.

    Preserves `onboarded_at` (set by the agent via `wbox skills mark-onboarded`).
    """
    now = datetime.now(timezone.utc).isoformat()
    existing = read_firm_meta()
    new_meta: dict[str, Any] = {
        "identity": identity,
        "cli_version": cli_version,
        "files": {name: now for name in generated_files},
    }
    onboarded_at = existing.get("onboarded_at")
    if onboarded_at:
        new_meta["onboarded_at"] = onboarded_at
    write_firm_meta(new_meta)


def mark_firm_onboarded() -> str:
    """Stamp `onboarded_at` in canonical firm meta. Returns the timestamp.

    Raises FileNotFoundError if no firm meta exists yet (caller must run
    `wbox skills bootstrap` before marking onboarded).
    """
    meta = read_firm_meta()
    if not meta:
        raise FileNotFoundError(
            f"{firm_meta_path()} does not exist; run 'wbox skills bootstrap' first."
        )
    now = datetime.now(timezone.utc).isoformat()
    meta["onboarded_at"] = now
    write_firm_meta(meta)
    return now


# --------------------------------------------------------------------------- #
# Migration: legacy <skill_dir>/firm/ + meta.firm  ->  canonical               #
# --------------------------------------------------------------------------- #

def migrate_legacy_firm(skill_dirs: list[Path]) -> Path | None:
    """If legacy firm/ data exists in any skill dir, move it to the canonical
    location. Returns the source skill_dir migrated from, or None if nothing
    was migrated.

    Strategy when multiple legacy installs exist: pick the one with the most
    recent `onboarded_at`, falling back to the most recent `files` timestamp.
    The other legacy installs are left in place (the doctor command surfaces
    them so the user can clean up at their leisure).
    """
    if firm_meta_path().exists() or firm_dir().is_dir():
        return None

    candidates: list[tuple[Path, dict[str, Any]]] = []
    for sd in skill_dirs:
        legacy_meta = read_meta(sd).get("firm")
        legacy_dir = sd / "firm"
        if legacy_meta or legacy_dir.is_dir():
            candidates.append((sd, legacy_meta or {}))

    if not candidates:
        return None

    def _key(item: tuple[Path, dict[str, Any]]) -> str:
        firm = item[1]
        ts = firm.get("onboarded_at") or ""
        if not ts:
            files = firm.get("files") or {}
            ts = max(files.values(), default="")
        return ts

    source_dir, source_firm = max(candidates, key=_key)

    legacy_firm_dir = source_dir / "firm"
    if legacy_firm_dir.is_dir():
        firm_dir().mkdir(parents=True, exist_ok=True)
        for entry in legacy_firm_dir.iterdir():
            dest = firm_dir() / entry.name
            if entry.is_dir():
                shutil.copytree(entry, dest, dirs_exist_ok=True)
            else:
                shutil.copy2(entry, dest)

    if source_firm:
        write_firm_meta(source_firm)

    return source_dir


# --------------------------------------------------------------------------- #
# Orchestrator                                                                 #
# --------------------------------------------------------------------------- #

import asyncio  # noqa: E402
from dataclasses import dataclass  # noqa: E402
from importlib.metadata import version as _pkg_version  # noqa: E402

from wealthbox_tools.client import WealthboxClient  # noqa: E402
from wealthbox_tools.models import CategoryListQuery, CategoryType, DocumentType  # noqa: E402

from ._util import get_client  # noqa: E402


@dataclass
class BootstrapResult:
    firm_dir: Path
    wrote_generated: list[str]
    wrote_stubs: int
    firm_identity: dict[str, Any]


async def _fetch_all(
    client: WealthboxClient,
) -> tuple[dict[str, list[dict[str, Any]]], dict[str, list[dict[str, Any]]], list[dict[str, Any]], dict[str, Any]]:
    categories: dict[str, list[dict[str, Any]]] = {}
    for ct in CategoryType:
        if ct is CategoryType.CUSTOM_FIELDS:
            continue
        resp = await client.list_all_categories(ct)
        categories[ct.value] = resp.get(ct.value, [])

    custom_fields: dict[str, list[dict[str, Any]]] = {}
    for dt in DocumentType:
        resp = await client.list_all_categories(
            CategoryType.CUSTOM_FIELDS,
            CategoryListQuery(document_type=dt),
        )
        custom_fields[dt.value] = resp.get("custom_fields", [])

    users_resp = await client.list_all_users()
    users = users_resp.get("users", [])

    me = await client.get_me()
    accounts = me.get("accounts") or []
    primary_account = accounts[0] if accounts else {}
    # Use workspace user (current_user.id), not the global account-user id —
    # records reference the former.
    current_user = me.get("current_user") or {}
    firm = {
        "id": primary_account.get("id"),
        "name": primary_account.get("name"),
        "user_id": current_user.get("id") or me.get("id"),
        "user_name": current_user.get("name") or me.get("name"),
    }
    return categories, custom_fields, users, firm


def bootstrap_firm(
    *,
    token: str | None,
    generated_only: bool,
) -> BootstrapResult:
    """Populate the canonical firm directory + meta from the Wealthbox API.

    Writes to `firm_dir()` (machine-level), not into any specific skill install.
    """
    target = firm_dir()
    target.mkdir(parents=True, exist_ok=True)

    async def _run() -> tuple[dict, dict, list, dict]:
        async with get_client(token) as client:
            return await _fetch_all(client)

    categories, custom_fields, users, firm_identity = asyncio.run(_run())

    (target / "categories.md").write_text(render_categories_md(categories), encoding="utf-8")
    (target / "custom-fields.md").write_text(render_custom_fields_md(custom_fields), encoding="utf-8")
    (target / "users.md").write_text(render_users_md(users), encoding="utf-8")

    generated = ["categories.md", "custom-fields.md", "users.md"]
    update_firm_meta(
        identity=firm_identity,
        cli_version=_pkg_version("wealthbox-cli"),
        generated_files=generated,
    )

    wrote_stubs = 0
    if not generated_only:
        wrote_stubs = len(write_stubs(target))
    else:
        readme = target / "_README.md"
        if not readme.exists():
            readme.write_text(FIRM_README, encoding="utf-8")

    return BootstrapResult(
        firm_dir=target,
        wrote_generated=generated,
        wrote_stubs=wrote_stubs,
        firm_identity=firm_identity,
    )
