from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def _escape(s: str) -> str:
    """Escape characters that would break a markdown table cell."""
    return s.replace("|", "\\|").replace("\n", " ")


def _md_table(headers: list[str], rows: list[list[str]]) -> str:
    if not rows:
        return "(no values)\n"
    out = ["| " + " | ".join(headers) + " |"]
    out.append("| " + " | ".join("---" for _ in headers) + " |")
    for row in rows:
        out.append("| " + " | ".join(_escape(str(c)) for c in row) + " |")
    return "\n".join(out) + "\n"


def render_categories_md(fetched: dict[str, list[dict[str, Any]]]) -> str:
    """Render every category type + its values as one markdown doc."""
    sections = [
        "# Firm Categories\n",
        "_Generated by `wbox skills bootstrap`. Refresh with `wbox skills refresh`._\n",
    ]
    for type_name in sorted(fetched):
        sections.append(f"## {type_name}\n")
        values = fetched[type_name]
        rows = [[str(v.get("id", "")), str(v.get("name", ""))] for v in values]
        sections.append(_md_table(["id", "name"], rows))
    return "\n".join(sections)


def render_custom_fields_md(fetched: dict[str, list[dict[str, Any]]]) -> str:
    """Render custom fields grouped by document type with valid options inline."""
    sections = [
        "# Firm Custom Fields\n",
        "_Generated by `wbox skills bootstrap`. Refresh with `wbox skills refresh`._\n",
    ]
    for doc_type in sorted(fetched):
        sections.append(f"## {doc_type}\n")
        fields = fetched[doc_type]
        rows: list[list[str]] = []
        for f in fields:
            options = f.get("options") or []
            option_names = (
                ", ".join(o.get("name", "") for o in options) if options else "—"
            )
            rows.append(
                [
                    str(f.get("id", "")),
                    str(f.get("name", "")),
                    str(f.get("field_type", "")),
                    option_names,
                ]
            )
        sections.append(_md_table(["id", "name", "type", "options"], rows))
    return "\n".join(sections)


def render_users_md(users: list[dict[str, Any]]) -> str:
    sections = [
        "# Firm Users\n",
        "_Generated by `wbox skills bootstrap`. Refresh with `wbox skills refresh`._\n",
    ]
    rows = [
        [str(u.get("id", "")), str(u.get("name", "")), str(u.get("email", ""))]
        for u in users
    ]
    if not rows:
        sections.append("(no users)\n")
    else:
        sections.append(_md_table(["id", "name", "email"], rows))
    return "\n".join(sections)


# --------------------------------------------------------------------------- #
# Stubs + meta.json                                                            #
# --------------------------------------------------------------------------- #

FIRM_README = """# firm/ — Firm Customizations

This folder holds everything the agent needs to know about your firm's
Wealthbox conventions.

## Generated files (overwritten by `wbox skills refresh`)

- `_meta.json` — refresh timestamps, firm identity, CLI version
- `categories.md` — every category type + valid values
- `custom-fields.md` — custom fields per document type + valid values
- `users.md` — user id → name → email

## Hand-edited files (never overwritten)

- `contacts.md`, `tasks.md`, `notes.md`, `events.md`,
  `opportunities.md`, `projects.md`, `workflows.md`

Each hand-edited file has a matching example at `../firm-examples/<name>`.
"""


def _stub(resource: str) -> str:
    return (
        f"# firm/{resource} — Firm Policy\n\n"
        f"_Stub — first-run bootstrap will populate this via the agent._\n\n"
        f"See `firm-examples/{resource}` for a filled-in reference.\n\n"
        f"TODO: capture firm policy for {resource[:-3]} here.\n"
    )


STUB_CONTENTS: dict[str, str] = {
    "contacts.md": _stub("contacts.md"),
    "tasks.md": _stub("tasks.md"),
    "notes.md": _stub("notes.md"),
    "events.md": _stub("events.md"),
    "opportunities.md": _stub("opportunities.md"),
    "projects.md": _stub("projects.md"),
    "workflows.md": _stub("workflows.md"),
}


def write_stubs(firm_dir: Path) -> list[str]:
    """Write stub files that don't already exist. Returns list of names written."""
    written: list[str] = []
    for name, body in STUB_CONTENTS.items():
        path = firm_dir / name
        if path.exists():
            continue
        path.write_text(body, encoding="utf-8")
        written.append(name)
    readme = firm_dir / "_README.md"
    if not readme.exists():
        readme.write_text(FIRM_README, encoding="utf-8")
    return written


def write_meta_json(
    firm_dir: Path,
    *,
    generated_files: list[str],
    firm_identity: dict[str, Any],
    cli_version: str,
) -> None:
    now = datetime.now(timezone.utc).isoformat()
    meta = {
        "firm": firm_identity,
        "cli_version": cli_version,
        "files": {name: now for name in generated_files},
    }
    (firm_dir / "_meta.json").write_text(
        json.dumps(meta, indent=2) + "\n", encoding="utf-8"
    )


# --------------------------------------------------------------------------- #
# Orchestrator                                                                 #
# --------------------------------------------------------------------------- #

import asyncio  # noqa: E402
from dataclasses import dataclass  # noqa: E402
from importlib.metadata import version as _pkg_version  # noqa: E402

from wealthbox_tools.client import WealthboxClient  # noqa: E402
from wealthbox_tools.models import CategoryListQuery, CategoryType, DocumentType  # noqa: E402


@dataclass
class BootstrapResult:
    skill_dir: Path
    wrote_generated: list[str]
    wrote_stubs: int
    firm_identity: dict[str, Any]


async def _fetch_all(
    client: WealthboxClient,
) -> tuple[dict[str, list[dict[str, Any]]], dict[str, list[dict[str, Any]]], list[dict[str, Any]], dict[str, Any]]:
    categories: dict[str, list[dict[str, Any]]] = {}
    for ct in CategoryType:
        if ct is CategoryType.CUSTOM_FIELDS:
            continue
        resp = await client.list_categories(ct)
        categories[ct.value] = resp.get(ct.value, [])

    custom_fields: dict[str, list[dict[str, Any]]] = {}
    for dt in DocumentType:
        resp = await client.list_categories(
            CategoryType.CUSTOM_FIELDS,
            CategoryListQuery(document_type=dt),
        )
        custom_fields[dt.value] = resp.get("custom_fields", [])

    users_resp = await client.list_users()
    users = users_resp.get("users", [])

    me = await client.get_me()
    firm = {
        "id": me.get("id"),
        "name": me.get("name"),
        "account": me.get("account"),
    }
    return categories, custom_fields, users, firm


def bootstrap_skill_dir(
    skill_dir: Path,
    *,
    token: str | None,
    generated_only: bool,
) -> BootstrapResult:
    firm_dir = skill_dir / "firm"
    firm_dir.mkdir(parents=True, exist_ok=True)

    async def _run() -> tuple[dict, dict, list, dict]:
        async with WealthboxClient(token=token) as client:
            return await _fetch_all(client)

    categories, custom_fields, users, firm_identity = asyncio.run(_run())

    (firm_dir / "categories.md").write_text(render_categories_md(categories), encoding="utf-8")
    (firm_dir / "custom-fields.md").write_text(render_custom_fields_md(custom_fields), encoding="utf-8")
    (firm_dir / "users.md").write_text(render_users_md(users), encoding="utf-8")

    generated = ["categories.md", "custom-fields.md", "users.md"]
    write_meta_json(
        firm_dir,
        generated_files=generated,
        firm_identity=firm_identity,
        cli_version=_pkg_version("wealthbox-cli"),
    )

    wrote_stubs = 0
    if not generated_only:
        wrote_stubs = len(write_stubs(firm_dir))
    else:
        readme = firm_dir / "_README.md"
        if not readme.exists():
            readme.write_text(FIRM_README, encoding="utf-8")

    return BootstrapResult(
        skill_dir=skill_dir,
        wrote_generated=generated,
        wrote_stubs=wrote_stubs,
        firm_identity=firm_identity,
    )
