from __future__ import annotations

from typing import Any


def _escape(s: str) -> str:
    """Escape characters that would break a markdown table cell."""
    return s.replace("|", "\\|").replace("\n", " ")


def _md_table(headers: list[str], rows: list[list[str]]) -> str:
    if not rows:
        return "(no values)\n"
    out = ["| " + " | ".join(headers) + " |"]
    out.append("| " + " | ".join("---" for _ in headers) + " |")
    for row in rows:
        out.append("| " + " | ".join(_escape(str(c)) for c in row) + " |")
    return "\n".join(out) + "\n"


def render_categories_md(fetched: dict[str, list[dict[str, Any]]]) -> str:
    """Render every category type + its values as one markdown doc."""
    sections = [
        "# Firm Categories\n",
        "_Generated by `wbox skills bootstrap`. Refresh with `wbox skills refresh`._\n",
    ]
    for type_name in sorted(fetched):
        sections.append(f"## {type_name}\n")
        values = fetched[type_name]
        rows = [[str(v.get("id", "")), str(v.get("name", ""))] for v in values]
        sections.append(_md_table(["id", "name"], rows))
    return "\n".join(sections)


def render_custom_fields_md(fetched: dict[str, list[dict[str, Any]]]) -> str:
    """Render custom fields grouped by document type with valid options inline."""
    sections = [
        "# Firm Custom Fields\n",
        "_Generated by `wbox skills bootstrap`. Refresh with `wbox skills refresh`._\n",
    ]
    for doc_type in sorted(fetched):
        sections.append(f"## {doc_type}\n")
        fields = fetched[doc_type]
        rows: list[list[str]] = []
        for f in fields:
            options = f.get("options") or []
            option_names = (
                ", ".join(o.get("name", "") for o in options) if options else "—"
            )
            rows.append(
                [
                    str(f.get("id", "")),
                    str(f.get("name", "")),
                    str(f.get("field_type", "")),
                    option_names,
                ]
            )
        sections.append(_md_table(["id", "name", "type", "options"], rows))
    return "\n".join(sections)


def render_users_md(users: list[dict[str, Any]]) -> str:
    sections = [
        "# Firm Users\n",
        "_Generated by `wbox skills bootstrap`. Refresh with `wbox skills refresh`._\n",
    ]
    rows = [
        [str(u.get("id", "")), str(u.get("name", "")), str(u.get("email", ""))]
        for u in users
    ]
    if not rows:
        sections.append("(no users)\n")
    else:
        sections.append(_md_table(["id", "name", "email"], rows))
    return "\n".join(sections)
